# Site settings
title: CWI Eventos
description: >
  Site para divulgação de eventos de desenvolvimento de software, tecnologia e design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eventos.cwi.com.br" # the base hostname & protocol for your site
github_username: CWISoftware
exclude: [
  node_modules,
  package.json,
  npm-debug.log,
  scss,
  README.md,
  docs,
  webpack.config.js
]

# Build settings
markdown: kramdown
