# Site settings
title: CWI Eventos
description: >
  Eventos de desenvolvimento de software, tecnologia e design
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eventos.cwi.com.br" # the base hostname & protocol for your site
github_username: CWISoftware
exclude: [
  # folders
  config,
  docs,
  gulp,
  node_modules,
  scss,
  src,
  test,

  # files
  gulpfile.babel.js,
  npm-debug.log,
  package.json,
  README.md,
  webpack.config.js
]

# Build settings
markdown: kramdown
